### ISSUE TITLE
[Feature Suggestion] Create Small Separators Between Actors

### ISSUE THREAD

**Issue by GhostwheelX** [CristianVasile23/conversation-hud#13]
I think it could be cool if we could create small headbars between actors to allow for better visibility when having conversations between many separate parties in the same conversation.

**Comment by CristianVasile23** [comment]
That is a nice suggestion, I will be looking into adding something like this in the future. I don't know if it will be under the form of a separator (as that might make things look awkward when you will also have the option to re-order participants) which is why I am thinking of something more like a faction banner or symbol near the portrait itself. But who knows, I will try some things out and see what works and looks best.

**Comment by CristianVasile23** [comment]
So with the v5 release of the module, I have introduced the option of configuring and attaching a faction to each participant. This feature, combined with the ability to re-order participants should help to create a visible distinction between multiple parties present in the same conversation.

I have also played around with the idea of adding separators, I think I have found an option that might work (I need to test it further), but for now I think the addition of factions should help you achieve what you have suggested (until that separator is also implemented).

If you have any questions or additional requests/suggestions, feel free to contact me and I will answer as best as I can.
