### ISSUE TITLE
[Feature Request] Roleplay notes/integration with monks journals

### ISSUE THREAD

**Issue by Orionox** [CristianVasile23/conversation-hud#22]
Would be really cool if when you are having a conversation if a small not pad could show up next to each character for the GM and display some roleplay notes. These notes could be typed in manually or pulled from somewhere on the monks enhanced journal sheets.

**Comment by CristianVasile23** [comment]
I have added the option to link a journal entry to each participant from a conversation. When creating/editing a participant, you will be able to see a dropdown with all the journal entries in the world, simply select one and you will be able to see an additional button during active conversations which will open the selected sheet (MEJ entries are supported as well so you should be able to link any journal entry you want).

![image](https://github.com/CristianVasile23/conversation-hud/assets/51834117/012687d1-5e6a-41b8-bdda-3b4aa23d02f5)
![3](https://github.com/CristianVasile23/conversation-hud/assets/51834117/51fbcac4-7d16-47f7-b55c-f5de5fcc0ae3)

Initially I wanted to display the notes inside the conversation itself, however that would never have worked due to the limited amount of space (as I am trying to make the module compatible for smaller screens as well). As such, having a separate popup for the linked sheet was the only feasible solution that I could find. Hopefully this works for you.
