### ISSUE TITLE
Sceen Setting to turn on Conversation HUD automatically

### ISSUE THREAD

**Issue by apoapostolov** [CristianVasile23/conversation-hud#25]
Please add per scene setting to turn on Conversation HUD automatically and to use one of the premade journals with conversation setups automatically. Changing to another scene with Conversation HUD on but different setup changes the setup. Changing to another scene with Conversation HUD off turns off the Conversation HUD.

This will speed up preparation a lot.

**Comment by CristianVasile23** [comment]
I will look into something like this but I don't know if I will be adding this feature as I have a couple of reservations.

Firstly, I don't know if the effort needed for something like this is worth it considering it takes a couple of seconds to manually activate a conversation (even less so if you already have notes and you embed the conversation in those notes). Thus, if it's something that might take a considerable time of effort to add then I don't know if it's really worth it.

Secondly, I don't really want to mess with the scene configuration, I am trying to alter as little as possible with this module so as to ensure compatibility with as many systems/modules as possible. Editing the scene object itself might cause some issues. (Granted, in theory there shouldn't be a lot of compatibility issues but you never know).

And finally, if I am to add this automatic toggle on/off depending on how a scene is configured and if it has a linked conversation or not. The issue lies with the automatic deactivation as there might be situations you want to change a scene and still keep the active conversation. 

That said, I will look into this and see if there is a way to add what you have requested in a reasonable amount of time without too much effort (since I do think this request falls a bit out of the scope of this module). No promises however.

In the meantime, I highly suggest using the journal embed feature to start conversations, this is how I do it in my games and I think it works really well. Just drag and drop a conversation into one of your notes and then CTRL + LClick to activate. You can even drag a scene in the journal as well and then you can activate both the scene and the conversation and pretty much achieve the same result as what you have requested while also having your notes open for additional information (dialogue, character traits, etc.).

**Comment by CristianVasile23** [comment]
Hey there and sorry for the long delay, this took way longer than I wanted to but I just couldn't get around to working on the module. I am pleased to tell you that with release 5.2.0 you can now link conversations to scenes as per your request. You can find the new input under the _Ambience_ tab of the _Scene Config_ menu and in that input you can select all of the currently saved conversation sheets.

There are however a couple of things to note:
1 - Conversations will turn on automatically only when you activate a scene. This is to prevent them from appearing when you simply want to view a scene.
2 - When switching scenes, if you activate a scene that has no conversation, the currently active one will remain open. This is because I feel that there are cases where you might want to activate another scene and still keep the currently open conversation. Overall, I do not think it's a big issue considering that now you can quickly close conversations from the right side menu.
3 - If you for some reason log out and rejoin the application and the currently active scene has a conversation linked, this conversation will not appear automatically. This is a technical limitation which is why I also added a button on the _Scene Config_ that will activate the linked conversation. This point is only an issue when there are no other users online, if there are other uses then there shouldn't be any issues as the currently active conversation will be fetched from the others.

With that long wall of text out of the way, if you have any other questions or suggestions, feel free to reach out!

**Comment by apoapostolov** [comment]
Thank you very much for this amazing feature!
