### ISSUE TITLE
[Feature Request] Option to hide NPC list from players

### ISSUE THREAD

**Issue by davidhawbecker** [CristianVasile23/conversation-hud#39]
I love the concept of this module for social interaction. I was just curious if there was a way to hide the list of the NPC on the side of the main portrait from the players. The reason is that sometimes I may not want to telegraph to the players who all the NPC's are in the scene. Sometime that might be useful, but others I'd like them to just interact with whoever I have on there screen instead of "who else" is in the scene.

**Comment by CristianVasile23** [comment]
Hey there! The option to hide the list of conversation participants has just been added in the latest major release of this module. To enable it, all you must do is go to the module settings and disable the _Display Participants List_ feature just like in the screenshot attached.

![DisplayParticipantsList](https://github.com/CristianVasile23/conversation-hud/assets/51834117/b7e567e9-ce83-46d0-9d1d-cd61a6d681cc)

This will make it so that the players will only be able do see the currently active speaker.

I will close this issue as the feature already exists, but if you encounter any problems or have any other questions feel free to reach out and I will help.

**Comment by davidhawbecker** [comment]
Dude, this is awesome. And the response here is epic. I assume this was already in the works, otherwise big thank you for the increible response time and support. Thank you.
