### ISSUE TITLE
feature requests - background image, remove box border, open token option. 

### ISSUE THREAD

**Issue by DiceKnights** [CristianVasile23/conversation-hud#53]
Loving your work on this module. I've tried others with more visual bells and whistles, but they take a lot more effort  to set up and maintain from a GM perspective.  I really appreciate the simplicity of Conversation HUD.  I do have some suggestions for possible features I think would be useful. 

**Background Images** 
An option to display a background image, rather than blurring the scene, perhaps an option to display a background image. For example if you are on a battle map, and tokens scene, would be cool when you fire up a conversation it overlays the screen with a background image of the location (which could be selected when setting up the conversation).  For example say your battle map is exploring the back alleys of a city, you start the conversation and it puts up an image of an alley (rather than just blurring the map).  Its the one thing I really found useful from Visual Novel Dialogues. 

**Remove the Box Border**
It would be nice to be able to display the picture without having the big shaded out box around it.  Including being able to display nothing at all if no participant is selected (rather than a big empty box stating no active participant.   That way you could start conversation HUD (and it would change to the background image as suggested above without a big empty box in  the middle) and then when you introduce the NPC you can select the participant to speak as and display their image. 

**Open Token / Interact with Token**
Would be great  to be able to right click on the active participant to open its character sheet... or even better be able to target the active participant just like you would a normal token.  To be able to check relevant skills/abilities/personality traits during the convo.  The targeting would be useful for automation. For example in pathfinder 2e if you want to make any social skill checks (intimidate/coerce/sense motive etc) you target the token you are trying to influence and make you roll and it correctly takes their relevant stats into acct. I believe the 5e automation is similar. 

Sorry if it sounds like a laundry list of suggestions, I love the module and will use it regardless. These are just a few things I think would make it even better.

**Comment by CristianVasile23** [comment]
No worries, these are all good suggestions and I am always glad to have feedback.

Regarding the suggestions:
- The background images are currently something I am working on. It has been a feature that I wanted to add for some time and I am mostly done with it.
- I will be adding a toggle in the settings so that when no participant is active the box will no longer appear. That said, I will not be removing the border around the active participants. This is because I want to keep the style of the FoundryVTT UI, and all elements have that rounded border with shading. If you want to however, I can happily tell you how to edit out the border and shadow on your instance.
- For token interaction, I am working on a way to associate tokens to conversations and participants to actors. This will at the very least allow you to open the character sheet of participants. Based on how this feature turns out, maybe I can look into some of the automation features as well. I will look into it!

**Comment by CristianVasile23** [comment]
With version 5.6.0, I have added an option to associate actors to conversation participants, which will then allow you to access the actor sheet in a similar way to how you can access a linked journal note. Additionally, I have also added a configuration setting that disables the _No active participant_ box, you can find it in the settings and you can toggle it off as it is on by default.

Having actors now being linked, I will look for ways to maybe add another button that targets the actor's token, but that will come in a future update.

Regarding the border itself, like I said, if you want to remove it I can tell you how to do so, but in my opinion it will look a bit weird. Whatever the case, feel free to reach out and I will help you as best as I can.
