### ISSUE TITLE
[BUG] Background Image Changes/Toggling Background Image 

### ISSUE THREAD

**Issue by myzar472** [CristianVasile23/conversation-hud#57]
I'm not sure if this is intended behavior, but it appears that after a GM sets a background image and starts a conversation, toggling the background off and/or setting a new background will not render any changes for connected players.

In the first case, toggling a background would appear to change the background for the GM, but players do not see a change. In the second case, no change occurs.

**Comment by CristianVasile23** [comment]
Yes, this is indeed a bug. The good news are that I know why this happens and I will fix it soon, probably even by the end of the day. Thanks for bringing this to my attention.

**Comment by CristianVasile23** [comment]
The issue should be fixed with release 5.6.1, now all changes are also reflected for the other participants. If you encounter any other issues however, please feel free to reach out and I will help as soon as possible. And once again, thanks for bringing this up to my attention. It appears that I forgot to test the features added in 5.6.0 on multiple clients.
