### ISSUE TITLE
Feature Request: "Speak as" selected conversation participant in chat

### ISSUE THREAD

**Issue by buttonpushertv** [CristianVasile23/conversation-hud#8]
Would it be possible to automatically set the "Speaking as" value in chat based on the selected conversation participant?

**Comment by CristianVasile23** [comment]
I need to look into it, it might be possible but I do not know at the moment (The fact that some participants might not have associated actors could cause issues). I will investigate and if it's doable I will add this feature whenever I get some time.

**Comment by CristianVasile23** [comment]
Oh, thanks for the tip, I will be looking into that to see how it works. I assumed that you can edit a chat message so that it can display whatever name you want it to, but I wasn't 100% sure. But since it appears to have been done already, that means it's 100% doable and I will be adding this feature whenever I have some free time.
Thanks for the suggestion by the way!

**Comment by CristianVasile23** [comment]
I have added a _Speak As_ toggle with release 3.5.0. Now whenever you have a conversation open, you can toggle this feature on and all chat messages will be sent under the name of the currently active participant. You will find said toggle with the rest of the conversation controls. Additionally, should you have any use for it, I have also added a macro that toggles this feature on/off.
